--CREATE TABLE News(
--    id int generated by default as identity primary key,
--    category varchar(255),
--    content text,
--    creation_date TIMESTAMP WITHOUT TIME ZONE,
--    headline varchar(255),
--    author_id varchar(255)
--);
--
--CREATE INDEX category_index ON News (category);

CREATE TABLE Comment(
    id int generated by default as identity primary key,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    text varchar(255),
    news_id int,
    author_id int
);